version: '1.0.0'
services:
  mariadb:
    image: mariadb:latest
    container_name: users_db
    environment:
      MARIADB_DATABASE: mydatabase
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: myuser
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - user-microservice-network
    restart: always
  spring-app:
    container_name: users-microservice
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - user-microservice-network
    restart: always
networks:
  user-microservice-network:
volumes:
  mariadb_data:
